name: Python CI Steps
description: Install, lint, and test Django app
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
      shell: bash

    - name: Run pre-commit
      run: pre-commit run --all-files --show-diff-on-failure
      shell: bash

    - name: Run tests
      run: pytest
      shell: bash
