name: Django CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: tests.settings

    steps:
      - uses: ./.github/workflows/python-ci
